In [425]:
from __future__ import division
import numpy as np
import scipy.misc
import os
from torch.utils.data import DataLoader
import torch.nn as nn
from torch.autograd import Variable
from SR_datasets import SRCNN_dataset, SR_dataset

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [13]:
os.getcwd()


'/mnt/hdd1/thangvubk/workspace/NeuralNetwork/NeuralNetworkProject/VSR'

In [1]:
from SR_datasets import *

dataset = SRCNN_dataset(os.getcwd()+'/akiyo', phase='train')

In [3]:
len(dataset.paths)


300

In [7]:
from config import *


In [8]:
config.SRCNN_IMG_DIFF


12

In [9]:
SRCNN_IMG_DIFF


12

In [13]:
a = np.fromfunction(lambda i, j: i + j, (8, 8), dtype=int)

In [38]:
import scipy.ndimage
b = scipy.ndimage.interpolation.zoom(a, 1/2, prefilter=False)

/mnt/hdd1/thangvubk/workspace/.global_env/local/lib/python2.7/site-packages/scipy/ndimage/interpolation.py:600: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
  "the returned array has changed.", UserWarning)


In [41]:
b

array([[[ 1],
        [ 3],
        [ 5],
        [ 7]],

       [[ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[ 5],
        [ 7],
        [ 9],
        [11]],

       [[ 7],
        [ 9],
        [11],
        [13]]])

In [20]:
c = scipy.ndimage.interpolation.zoom(b, 2, prefilter=False)

In [21]:
c

array([[ 2,  3,  3,  4,  5,  6,  7,  7],
       [ 3,  3,  4,  5,  5,  6,  7,  7],
       [ 3,  4,  4,  5,  6,  7,  8,  8],
       [ 4,  5,  5,  6,  7,  8,  9,  9],
       [ 5,  5,  6,  7,  8,  9,  9, 10],
       [ 6,  6,  7,  8,  9, 10, 10, 11],
       [ 7,  7,  8,  9,  9, 10, 11, 11],
       [ 7,  7,  8,  9, 10, 11, 11, 12]])

In [24]:
type(4//2)

int

In [30]:
import torchvision.transforms as T

In [31]:
transforms = T.ToTensor()

In [32]:
transforms

In [33]:
transforms = T.CenterCrop(20)

In [35]:
a = a[:, :, np.newaxis]

In [37]:
a.shape

(8, 8, 1)

In [426]:
dataset = SR_dataset(os.getcwd()+'/akiyo')

dataloader = DataLoader(dataset, batch_size=10, shuffle=False)

dataiter = iter(dataloader)

low, high = dataiter.next()
low = Variable(low)

In [427]:
low.size()


torch.Size([10, 1, 96, 117])

In [9]:
low.size()

torch.Size([10, 1, 288, 351])

In [377]:
a = scipy.misc.imread('Result/label_1.png', flatten=True, mode='YCbCr')

b = scipy.misc.imread('Result/output_1.png', flatten=True, mode='YCbCr')

imdiff = (a - b)

rmse = np.linalg.norm(imdiff)
rmse1 = np.sqrt(np.mean(imdiff**2))

psnr = 20*np.log10(255/rmse1)

In [378]:
psnr

25.384933635565275

In [361]:
20*np.log10(1/np.sqrt(0.00106))

29.746941347352298

In [358]:
np.sqrt(0.0012*256)

0.55425625842204074

In [218]:
87.39/39.26

2.225929699439633

In [311]:
a = scipy.misc.imread('akiyo2/image-0001.bmp', flatten=True, mode='YCbCr')

In [313]:
scipy.misc.imsave('akiyo2/temp.bmp', a)

In [314]:
b = scipy.misc.imread('akiyo2/temp.bmp', flatten=True, mode='YCbCr')

In [374]:
a


array([[ 252.,  252.,  251., ...,  253.,  253.,  253.],
       [ 253.,  252.,  250., ...,  251.,  251.,  253.],
       [ 252.,  251.,  250., ...,  251.,  251.,  253.],
       ..., 
       [ 112.,  111.,  106., ...,   53.,   42.,   50.],
       [ 116.,  112.,  104., ...,   61.,   47.,   49.],
       [ 111.,  104.,  101., ...,   58.,   48.,   44.]], dtype=float32)

In [369]:
b[:5, :5]

array([[ 41.,  42.,  42.,  42.,  42.],
       [ 40.,  40.,  40.,  41.,  41.],
       [ 39.,  39.,  40.,  40.,  40.],
       [ 40.,  40.,  40.,  41.,  41.],
       [ 41.,  41.,  42.,  42.,  42.]], dtype=float32)

In [318]:
from PIL import Image

In [320]:
a = Image.open('akiyo2/image-0001.bmp')


In [324]:
imga = a.convert('YCbCr')

In [336]:
with open('akiyo2/image-0001.bmp', 'rb') as f:
            with Image.open(f) as img:
                image = img.convert('YCbCr')

In [337]:
type(image)

PIL.Image.Image

In [341]:
img = np.array(image)

In [344]:
img[:, :, 0]

array([[36, 37, 39, ..., 26, 24,  3],
       [35, 37, 36, ..., 29, 25,  3],
       [36, 37, 36, ..., 26, 24,  3],
       ..., 
       [51, 51, 51, ..., 47, 45,  3],
       [51, 51, 51, ..., 47, 46,  3],
       [50, 50, 52, ..., 49, 44,  3]], dtype=uint8)

In [345]:
pilImg = Image.fromarray(img)

In [346]:
pilImg.save('akiyo2/temp.bmp')

In [347]:
with open('akiyo2/temp.bmp') as f:
            with Image.open(f) as img:
                image = img.convert('YCbCr')

In [348]:
img1= np.array(image)

In [349]:
img1[:, :, 0]

array([[ 98,  98,  99, ...,  93,  94,  89],
       [ 98,  98,  98, ...,  94,  94,  89],
       [ 98,  99,  98, ...,  95,  95,  89],
       ..., 
       [105, 105, 104, ..., 102, 101,  89],
       [105, 105, 104, ..., 102, 102,  89],
       [104, 104, 104, ..., 102, 101,  89]], dtype=uint8)

In [468]:

conv1 = nn.Conv2d(1, 32, 5)
conv2 = nn.Conv2d(32, 5, 1)
conv3 = nn.Conv2d(5, 5, 3)
conv4 = nn.Conv2d(5, 32, 1)
conv5 = nn.ConvTranspose2d(32, 1, 9, stride=3)
def forward(x):
    x = conv3(conv2(conv1(x)))
    x = conv4(x)
    x = conv5(x)
    return x

y = forward(low)

In [469]:
y.size()

torch.Size([10, 1, 276, 339])

In [417]:
low.size()



torch.Size([10, 1, 288, 351])

In [397]:
y.size()

torch.Size([10, 2, 284, 347])

In [400]:
deconv = nn.ConvTranspose2d(2, 1, 5)

In [401]:
low_temp = deconv(y)

In [402]:
low_temp.size()

torch.Size([10, 1, 288, 351])

In [404]:
low_temp

Variable containing:
( 0 , 0 ,.,.) = 
 -1.0126e-01 -1.2886e-01 -1.0082e-01  ...  -8.5247e-02 -1.1212e-01 -1.1804e-01
 -1.2935e-01 -1.5089e-01 -1.0386e-01  ...  -4.6491e-02 -9.0805e-02 -1.1252e-01
 -9.8513e-02 -1.2316e-01 -7.7634e-02  ...  -4.2536e-02 -8.5441e-02 -1.0851e-01
                 ...                   ⋱                   ...                
 -1.2824e-01 -1.1765e-01 -9.0062e-02  ...  -1.2554e-01 -1.5207e-01 -1.2638e-01
 -1.6437e-01 -1.5320e-01 -1.2554e-01  ...  -1.2826e-01 -1.5536e-01 -1.2911e-01
 -1.5517e-01 -1.5938e-01 -1.7557e-01  ...  -1.5153e-01 -1.3667e-01 -1.2795e-01
      ⋮  

( 1 , 0 ,.,.) = 
 -1.0126e-01 -1.2886e-01 -1.0082e-01  ...  -8.5243e-02 -1.1212e-01 -1.1804e-01
 -1.2935e-01 -1.5089e-01 -1.0386e-01  ...  -4.6481e-02 -9.0797e-02 -1.1251e-01
 -9.8513e-02 -1.2316e-01 -7.7634e-02  ...  -4.2518e-02 -8.5428e-02 -1.0851e-01
                 ...                   ⋱                   ...                
 -1.2824e-01 -1.1765e-01 -9.0062e-02  ...  -1.2554e-01 -1.5207e-0

In [405]:
low

Variable containing:
( 0 , 0 ,.,.) = 
  0.1370  0.1371  0.1374  ...   0.1015  0.1007  0.1003
  0.1361  0.1362  0.1364  ...   0.1021  0.1012  0.1008
  0.1338  0.1337  0.1335  ...   0.1032  0.1022  0.1018
           ...             ⋱             ...          
  0.1980  0.1985  0.1996  ...   0.1789  0.1783  0.1782
  0.1978  0.1984  0.1997  ...   0.1791  0.1785  0.1784
  0.1978  0.1984  0.1997  ...   0.1793  0.1787  0.1785
      ⋮  

( 1 , 0 ,.,.) = 
  0.1370  0.1371  0.1374  ...   0.1015  0.1007  0.1003
  0.1361  0.1362  0.1364  ...   0.1021  0.1012  0.1008
  0.1338  0.1337  0.1335  ...   0.1032  0.1022  0.1018
           ...             ⋱             ...          
  0.1980  0.1985  0.1996  ...   0.1789  0.1783  0.1782
  0.1978  0.1984  0.1997  ...   0.1791  0.1785  0.1784
  0.1978  0.1984  0.1997  ...   0.1793  0.1787  0.1785
      ⋮  

( 2 , 0 ,.,.) = 
  0.1370  0.1371  0.1375  ...   0.1015  0.1007  0.1003
  0.1362  0.1362  0.1364  ...   0.1021  0.1012  0.1008
  0.1338  0.1337  0.1335  

In [412]:
class a(object):
    def __init__(self, temp):
        self.temp = temp
class b(a):
    pass

var = b('temp')

In [411]:
var.temp

'temp'

In [470]:
ls

akiyo/      main.py    SCRNN_trained_model.pt  SR_datasets.pyc   Untitled.ipynb
akiyo2/     model.py   solver.py               Test/
config.py   model.pyc  solver.pyc              Train/
config.pyc  Result/    SR_datasets.py          trained_model.pt


In [471]:
os.path.exists('trained_model.pt')

True